import { useState } from 'react';
import {
  ChevronDown, ChevronRight, Truck, ShoppingCart, PackageCheck,
  MapPin, Box, Send, RotateCcw, Edit2, Tag, Printer, Copy,
} from 'lucide-react';
import { ItemNotes } from './ItemNotes.jsx';
import { BoxContentBadges } from './BoxContentBadges.jsx';
import { BoxNotePanel } from './BoxNotePanel.jsx';
import { BoxPackagingPanel } from './BoxPackagingPanel.jsx';
import { ShippingMarginNote } from './ShippingMarginNote.jsx';
import { openLabelPdf, copyText } from './labelPdf.js';

// One row of the packing list: recipient + items + label/ship actions.
// All the buy/void/ship/tracking handlers come from the parent so this
// stays a pure presentation component.
//
// Two label flows:
//   USPS — buyer's USPS label is generated by Palmstreet, the operator
//          downloads it from Palmstreet and pastes the tracking # here.
//   UPS  — bought from ShipStation via /api/shipstation; the row holds
//          the label PDF (in Storage) and the tracking #.
export function ShipBoxCard({
  box, shipment, showToast,
  onShip,
  onBuyLabel, onVoidLabel,
  onSaveTracking, onClearTracking,
  onPrintItemLabels,
  onSaveNote,
  boxSizes, onSavePackaging, onBought,
}) {
  const [open, setOpen] = useState(true);
  const [editingTracking, setEditingTracking] = useState(false);
  const [trackingInput, setTrackingInput] = useState('');
  const [savingTracking, setSavingTracking] = useState(false);
  const [trackingErr, setTrackingErr] = useState('');

  const allShipped = box.items.every(i => ['shipped', 'delivered'].includes(i.status));
  const hasActiveLabel = shipment && !shipment.voidedAt;
  const isUps = box.carrier === 'ups';
  const isUsps = box.carrier === 'usps';
  // Distinguish a Palmstreet-USPS row (operator-entered tracking) from a
  // ShipStation USPS row (rare but legal — operator could buy USPS
  // through ShipStation if they wanted). The carrierCode tells us.
  const isPalmstreetRow = shipment?.carrierCode === 'palmstreet';

  const a = box.address || {};
  const addressLine = [
    a.street1,
    a.street2,
    [a.city, a.state, a.zip].filter(Boolean).join(', '),
    a.country && a.country !== 'US' ? a.country : null,
  ].filter(Boolean).join(' · ');

  const beginEditTracking = () => {
    setTrackingInput(shipment?.trackingNumber || '');
    setTrackingErr('');
    setEditingTracking(true);
  };
  const cancelEditTracking = () => {
    setEditingTracking(false);
    setTrackingErr('');
  };
  const submitTracking = async () => {
    const trim = trackingInput.trim();
    if (!trim) { setTrackingErr('Tracking number required'); return; }
    setSavingTracking(true);
    setTrackingErr('');
    try {
      await onSaveTracking?.(box, trim);
      setEditingTracking(false);
    } catch (e) {
      setTrackingErr(e?.message || 'Save failed');
    }
    setSavingTracking(false);
  };

  return (
    <div className={`bg-white border rounded-xl overflow-hidden ${
      allShipped ? 'border-emerald-300' : 'border-gray-200'
    }`}>
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-start gap-3 px-4 py-3 hover:bg-gray-50 text-left"
      >
        <div className="mt-0.5 text-gray-400">
          {open ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium text-gray-900">{box.recipientName}</span>
            {box.username && <span className="text-xs text-gray-500">@{box.username}</span>}
            {box.carrier && (
              <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-1.5 py-0.5 rounded border ${
                isUps
                  ? 'text-amber-800 bg-amber-50 border-amber-200'
                  : 'text-blue-800 bg-blue-50 border-blue-200'
              }`}>
                <Truck className="w-3 h-3" /> {box.carrier.toUpperCase()}
              </span>
            )}
            <BoxContentBadges box={box} />
            {a.shipmentMethod && (
              <span className="inline-flex items-center gap-1 text-[11px] text-gray-600 bg-gray-100 px-1.5 py-0.5 rounded">
                {a.shipmentMethod}
              </span>
            )}
            {hasActiveLabel && (
              <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-1.5 py-0.5 rounded border ${
                shipment.isTestLabel
                  ? 'text-amber-800 bg-amber-50 border-amber-200'
                  : 'text-emerald-800 bg-emerald-50 border-emerald-200'
              }`}>
                {isPalmstreetRow ? <Tag className="w-3 h-3" /> : <ShoppingCart className="w-3 h-3" />}
                {isPalmstreetRow ? 'Tracking' : `Label${shipment.isTestLabel ? ' (test)' : ''}`}
              </span>
            )}
            {allShipped && (
              <span className="inline-flex items-center gap-1 text-[11px] text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded border border-emerald-200">
                <PackageCheck className="w-3 h-3" /> Shipped
              </span>
            )}
          </div>
          {addressLine && (
            <div className="text-xs text-gray-500 mt-0.5 flex items-start gap-1">
              <MapPin className="w-3 h-3 mt-0.5 flex-shrink-0" />
              <span>{addressLine}</span>
            </div>
          )}
        </div>
        <div className="text-right flex-shrink-0">
          <div className="text-sm font-medium text-gray-900">
            {box.items.length} {box.items.length === 1 ? 'item' : 'items'}
          </div>
        </div>
      </button>

      {open && (
        <div className="border-t border-gray-100">
          <div className="divide-y divide-gray-100">
            {box.items.map(item => (
              <div key={item.id} className="px-4 py-2.5 flex items-start gap-3">
                {item.lotNumber
                  ? <span className="shrink-0 mt-0.5 min-w-[1.75rem] px-1 py-0.5 rounded bg-blue-600 text-white text-xs font-bold text-center tabular-nums" title="Lineup number">{item.lotNumber}</span>
                  : <Box className="w-3.5 h-3.5 text-gray-400 mt-0.5" />}
                <div className="flex-1 min-w-0">
                  <div className="text-sm text-gray-900 truncate">
                    {item.name}{item.variety ? ` · ${item.variety}` : ''}
                  </div>
                  <div className="text-xs text-gray-500 font-mono">
                    {item.sku}
                    {item.salePrice ? ` · $${parseFloat(item.salePrice).toFixed(2)}` : ''}
                  </div>
                  <ItemNotes raw={item.notes} />
                </div>
              </div>
            ))}
          </div>

          {/* Quote panel — hidden once a label is bought; reappears after
              the label is cancelled (hasActiveLabel flips back to false). */}
          {onSavePackaging && !allShipped && !hasActiveLabel && (
            <BoxPackagingPanel
              box={box}
              boxSizes={boxSizes}
              onSavePackaging={onSavePackaging}
              showToast={showToast}
              shipment={shipment}
              onBought={onBought}
            />
          )}

          {onSaveNote && (
            <BoxNotePanel
              note={box.note}
              onSave={onSaveNote}
              allShipped={allShipped}
              showToast={showToast}
            />
          )}

          {/* Inline USPS tracking editor — opens via "Add tracking" or "Edit". */}
          {editingTracking && (
            <div className="px-4 py-3 bg-blue-50 border-t border-blue-100 space-y-2">
              <div className="text-xs font-medium text-blue-900 flex items-center gap-1.5">
                <Tag className="w-3.5 h-3.5" /> USPS tracking number from Palmstreet
              </div>
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={trackingInput}
                  onChange={(e) => setTrackingInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') { e.preventDefault(); submitTracking(); }
                    if (e.key === 'Escape') cancelEditTracking();
                  }}
                  placeholder="9400 1112 0204 1234 5678 90"
                  autoFocus
                  className="flex-1 px-3 py-2 text-sm font-mono border border-blue-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                />
                <button
                  onClick={submitTracking}
                  disabled={savingTracking}
                  className="px-3 py-2 text-sm font-medium bg-blue-600 hover:bg-blue-700 disabled:bg-gray-300 text-white rounded-lg"
                >
                  {savingTracking ? 'Saving…' : 'Save'}
                </button>
                <button
                  onClick={cancelEditTracking}
                  className="px-3 py-2 text-sm text-gray-700 hover:bg-blue-100 rounded-lg"
                >
                  Cancel
                </button>
              </div>
              {trackingErr && (
                <div className="text-xs text-red-700">{trackingErr}</div>
              )}
            </div>
          )}

          {/* Existing-label info row. Same layout for both flows; the
              available actions differ. */}
          {hasActiveLabel && !editingTracking && (
            <div className="px-4 py-2.5 bg-gray-50 border-t border-gray-100 flex items-center gap-3 flex-wrap text-xs">
              {/* Tracking number — click to copy. */}
              {shipment.trackingNumber ? (
                <button
                  type="button"
                  onClick={() => copyText(shipment.trackingNumber, showToast)}
                  title="Copy tracking number"
                  className="flex items-center gap-1.5 text-gray-700 hover:text-emerald-700 group"
                >
                  <Truck className="w-3.5 h-3.5 text-gray-500 group-hover:text-emerald-600" />
                  <span className="font-mono">{shipment.trackingNumber}</span>
                  <Copy className="w-3 h-3 text-gray-400 group-hover:text-emerald-600" />
                </button>
              ) : (
                <div className="flex items-center gap-1.5 text-gray-500">
                  <Truck className="w-3.5 h-3.5 text-gray-400" />
                  <span className="font-mono">(no tracking)</span>
                </div>
              )}
              <span className="text-gray-400">
                {isPalmstreetRow ? 'Palmstreet USPS' : shipment.serviceCode}
              </span>
              <ShippingMarginNote
                feeCollected={box.shippingFeeCollected}
                cost={shipment.isTestLabel || shipment.labelCost == null ? null : parseFloat(shipment.labelCost)}
              />
              <div className="ml-auto flex items-center gap-1">
                {/* Label PDF — exists for ShipStation/Shippo rows AND for
                    Palmstreet rows that came through the Chrome extension. */}
                {(shipment.labelStoragePath || (!isPalmstreetRow)) && (
                  <button
                    onClick={() => openLabelPdf(shipment, 'label', showToast)}
                    className="flex items-center gap-1 px-2 py-1 text-emerald-700 hover:bg-emerald-50 rounded"
                  >
                    <Printer className="w-3.5 h-3.5" /> Print label
                  </button>
                )}
                {/* Packing slip — only Palmstreet flow currently provides this. */}
                {shipment.shippingSlipStoragePath && (
                  <button
                    onClick={() => openLabelPdf(shipment, 'slip', showToast)}
                    className="flex items-center gap-1 px-2 py-1 text-emerald-700 hover:bg-emerald-50 rounded"
                  >
                    <Printer className="w-3.5 h-3.5" /> Slip
                  </button>
                )}
                {!allShipped && isPalmstreetRow && (
                  <>
                    <button
                      onClick={beginEditTracking}
                      className="flex items-center gap-1 px-2 py-1 text-gray-700 hover:bg-gray-100 rounded"
                    >
                      <Edit2 className="w-3.5 h-3.5" /> Edit
                    </button>
                    <button
                      onClick={onClearTracking}
                      className="flex items-center gap-1 px-2 py-1 text-gray-600 hover:bg-red-50 hover:text-red-600 rounded"
                    >
                      <RotateCcw className="w-3.5 h-3.5" /> Clear
                    </button>
                  </>
                )}
                {!isPalmstreetRow && (
                  <button
                    onClick={onVoidLabel}
                    className="flex items-center gap-1 px-2 py-1 text-gray-600 hover:bg-red-50 hover:text-red-600 rounded"
                  >
                    <RotateCcw className="w-3.5 h-3.5" /> Cancel label
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Action buttons: differ by carrier. UPS gets the ShipStation
              Buy Label button; USPS gets a Palmstreet tracking entry button. */}
          {!allShipped && !editingTracking && (
            <div className="px-4 py-3 bg-gray-50 border-t border-gray-100 flex justify-end gap-2 flex-wrap">
              {onPrintItemLabels && (() => {
                // Same predicate as the tab-level button and the
                // BoxLabelSheet header tag (src/labels/BoxLabelSheet.jsx).
                const antItems = (box.items || []).filter(
                  i => (i.variety || '').toLowerCase() === 'anthurium'
                );
                if (antItems.length === 0) return null;
                return (
                  <button
                    type="button"
                    onClick={() => onPrintItemLabels(antItems)}
                    className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 text-sm font-medium rounded-lg"
                    title={`Print 2″×1″ labels for the ${antItems.length} Anthurium item${antItems.length === 1 ? '' : 's'} in this box`}
                  >
                    <Printer className="w-4 h-4" />
                    Print ANT labels
                    <span className="text-xs text-gray-500 ml-0.5">· {antItems.length}</span>
                  </button>
                );
              })()}
              {!hasActiveLabel && isUps && (
                <button
                  onClick={onBuyLabel}
                  className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-emerald-300 text-emerald-700 hover:bg-emerald-50 text-sm font-medium rounded-lg"
                >
                  <ShoppingCart className="w-4 h-4" /> Buy UPS Label
                </button>
              )}
              {!hasActiveLabel && isUsps && (
                <button
                  onClick={beginEditTracking}
                  className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-blue-300 text-blue-700 hover:bg-blue-50 text-sm font-medium rounded-lg"
                  title="Generate the label in Palmstreet, then paste the tracking number here"
                >
                  <Tag className="w-4 h-4" /> Add USPS Tracking
                </button>
              )}
              <button
                onClick={onShip}
                className="flex items-center gap-1.5 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 active:bg-emerald-800 text-white text-sm font-medium rounded-lg"
              >
                <Send className="w-4 h-4" /> Mark Shipped
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
