import { useState } from 'react';
import {
  ChevronDown, ChevronRight, Truck, ShoppingCart, PackageCheck,
  MapPin, Box, Send, RotateCcw, Download as DownloadIcon, Edit2, Tag, Printer,
  StickyNote, Pencil,
} from 'lucide-react';
import { api } from '../api.js';
import { ItemNotes } from './ItemNotes.jsx';
import { BoxContentBadges } from './BoxContentBadges.jsx';

// Fetch a fresh signed URL for one of the shipment PDFs (label or slip)
// and open it in a new tab. Falls back to a Blob download for legacy
// data: URLs (pre-Storage rows) since direct <a href="data:..."> downloads
// don't always trigger correctly.
async function downloadShipmentPdf(shipment, kind, showToast) {
  try {
    const url = await api.getLabelUrl(shipment.id, kind);
    if (url.startsWith('data:')) {
      const base64 = url.split(',')[1] || '';
      const bytes = atob(base64);
      const buf = new Uint8Array(bytes.length);
      for (let i = 0; i < bytes.length; i++) buf[i] = bytes.charCodeAt(i);
      const blob = new Blob([buf], { type: 'application/pdf' });
      const blobUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = blobUrl;
      a.download = `${kind}-${shipment.trackingNumber || shipment.id}.pdf`;
      a.click();
      URL.revokeObjectURL(blobUrl);
    } else {
      window.open(url, '_blank', 'noopener');
    }
  } catch (e) {
    showToast?.(e.message || `Could not open ${kind}`);
  }
}

// One row of the packing list: recipient + items + label/ship actions.
// All the buy/void/ship/tracking handlers come from the parent so this
// stays a pure presentation component.
//
// Two label flows:
//   USPS — buyer's USPS label is generated by Palmstreet, the operator
//          downloads it from Palmstreet and pastes the tracking # here.
//   UPS  — bought from ShipStation via /api/shipstation; the row holds
//          the label PDF (in Storage) and the tracking #.
export function ShipBoxCard({
  box, shipment, showToast,
  onShip,
  onBuyLabel, onVoidLabel,
  onSaveTracking, onClearTracking,
  onPrintItemLabels,
  onSaveNote,
}) {
  const [open, setOpen] = useState(true);
  const [editingTracking, setEditingTracking] = useState(false);
  const [trackingInput, setTrackingInput] = useState('');
  const [savingTracking, setSavingTracking] = useState(false);
  const [trackingErr, setTrackingErr] = useState('');
  const [editingNote, setEditingNote] = useState(false);
  const [noteInput, setNoteInput] = useState('');
  const [savingNote, setSavingNote] = useState(false);
  const [noteErr, setNoteErr] = useState('');

  const allShipped = box.items.every(i => ['shipped', 'delivered'].includes(i.status));
  const hasActiveLabel = shipment && !shipment.voidedAt;
  const isUps = box.carrier === 'ups';
  const isUsps = box.carrier === 'usps';
  // Distinguish a Palmstreet-USPS row (operator-entered tracking) from a
  // ShipStation USPS row (rare but legal — operator could buy USPS
  // through ShipStation if they wanted). The carrierCode tells us.
  const isPalmstreetRow = shipment?.carrierCode === 'palmstreet';

  const a = box.address || {};
  const addressLine = [
    a.street1,
    a.street2,
    [a.city, a.state, a.zip].filter(Boolean).join(', '),
    a.country && a.country !== 'US' ? a.country : null,
  ].filter(Boolean).join(' · ');

  const beginEditTracking = () => {
    setTrackingInput(shipment?.trackingNumber || '');
    setTrackingErr('');
    setEditingTracking(true);
  };
  const cancelEditTracking = () => {
    setEditingTracking(false);
    setTrackingErr('');
  };
  const submitTracking = async () => {
    const trim = trackingInput.trim();
    if (!trim) { setTrackingErr('Tracking number required'); return; }
    setSavingTracking(true);
    setTrackingErr('');
    try {
      await onSaveTracking?.(box, trim);
      setEditingTracking(false);
    } catch (e) {
      setTrackingErr(e?.message || 'Save failed');
    }
    setSavingTracking(false);
  };

  return (
    <div className={`bg-white border rounded-xl overflow-hidden ${
      allShipped ? 'border-emerald-300' : 'border-gray-200'
    }`}>
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-start gap-3 px-4 py-3 hover:bg-gray-50 text-left"
      >
        <div className="mt-0.5 text-gray-400">
          {open ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium text-gray-900">{box.recipientName}</span>
            {box.username && <span className="text-xs text-gray-500">@{box.username}</span>}
            {box.carrier && (
              <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-1.5 py-0.5 rounded border ${
                isUps
                  ? 'text-amber-800 bg-amber-50 border-amber-200'
                  : 'text-blue-800 bg-blue-50 border-blue-200'
              }`}>
                <Truck className="w-3 h-3" /> {box.carrier.toUpperCase()}
              </span>
            )}
            <BoxContentBadges box={box} />
            {a.shipmentMethod && (
              <span className="inline-flex items-center gap-1 text-[11px] text-gray-600 bg-gray-100 px-1.5 py-0.5 rounded">
                {a.shipmentMethod}
              </span>
            )}
            {hasActiveLabel && (
              <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-1.5 py-0.5 rounded border ${
                shipment.isTestLabel
                  ? 'text-amber-800 bg-amber-50 border-amber-200'
                  : 'text-emerald-800 bg-emerald-50 border-emerald-200'
              }`}>
                {isPalmstreetRow ? <Tag className="w-3 h-3" /> : <ShoppingCart className="w-3 h-3" />}
                {isPalmstreetRow ? 'Tracking' : `Label${shipment.isTestLabel ? ' (test)' : ''}`}
              </span>
            )}
            {allShipped && (
              <span className="inline-flex items-center gap-1 text-[11px] text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded border border-emerald-200">
                <PackageCheck className="w-3 h-3" /> Shipped
              </span>
            )}
          </div>
          {addressLine && (
            <div className="text-xs text-gray-500 mt-0.5 flex items-start gap-1">
              <MapPin className="w-3 h-3 mt-0.5 flex-shrink-0" />
              <span>{addressLine}</span>
            </div>
          )}
        </div>
        <div className="text-right flex-shrink-0">
          <div className="text-sm font-medium text-gray-900">
            {box.items.length} {box.items.length === 1 ? 'item' : 'items'}
          </div>
        </div>
      </button>

      {open && (
        <div className="border-t border-gray-100">
          <div className="divide-y divide-gray-100">
            {box.items.map(item => (
              <div key={item.id} className="px-4 py-2.5 flex items-start gap-3">
                <Box className="w-3.5 h-3.5 text-gray-400 mt-0.5" />
                <div className="flex-1 min-w-0">
                  <div className="text-sm text-gray-900 truncate">
                    {item.name}{item.variety ? ` · ${item.variety}` : ''}
                  </div>
                  <div className="text-xs text-gray-500 font-mono">
                    {item.sku}
                    {item.lotNumber ? ` · Lot #${item.lotNumber}` : ''}
                    {item.salePrice ? ` · $${parseFloat(item.salePrice).toFixed(2)}` : ''}
                  </div>
                  <ItemNotes raw={item.notes} />
                </div>
              </div>
            ))}
          </div>

          {/* Operator's internal seller-note. Single text field per box,
              edit overwrites, never printed. Lazy-persisted to
              shipment_boxes via api.setBoxNote. Hidden in edit form when
              the box is already shipped. */}
          {onSaveNote && (() => {
            const hasNote = !!(box.note && box.note.trim());
            const beginEdit = () => {
              setNoteInput(box.note || '');
              setNoteErr('');
              setEditingNote(true);
            };
            if (editingNote) {
              return (
                <div className="px-4 py-3 bg-amber-50 border-t border-amber-100 space-y-2">
                  <div className="text-[11px] uppercase tracking-wide text-amber-800 font-medium">Note</div>
                  <textarea
                    value={noteInput}
                    onChange={(e) => setNoteInput(e.target.value)}
                    rows={2}
                    autoFocus
                    placeholder="Operator note for this box (internal — not printed)"
                    className="w-full px-3 py-2 text-sm border border-amber-300 rounded-lg resize-y bg-white"
                  />
                  {noteErr && <div className="text-sm text-red-600">{noteErr}</div>}
                  <div className="flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={() => { setEditingNote(false); setNoteErr(''); }}
                      disabled={savingNote}
                      className="px-3 py-1.5 text-sm rounded-lg hover:bg-amber-100"
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      onClick={async () => {
                        setSavingNote(true);
                        setNoteErr('');
                        try {
                          await onSaveNote(noteInput);
                          setEditingNote(false);
                          showToast?.('Note saved', 1800);
                        } catch (e) {
                          setNoteErr(e.message || 'Save failed');
                        } finally {
                          setSavingNote(false);
                        }
                      }}
                      disabled={savingNote}
                      className="px-3 py-1.5 text-sm font-medium bg-amber-600 hover:bg-amber-700 text-white rounded-lg disabled:opacity-60"
                    >
                      Save
                    </button>
                  </div>
                </div>
              );
            }
            if (hasNote) {
              return (
                <div className="px-4 py-2.5 bg-amber-50 border-t border-amber-100 flex items-start gap-2">
                  <StickyNote className="w-3.5 h-3.5 text-amber-700 mt-0.5" />
                  <div className="flex-1 min-w-0 text-sm text-amber-900 whitespace-pre-wrap break-words">{box.note}</div>
                  {!allShipped && (
                    <button
                      type="button"
                      onClick={beginEdit}
                      title="Edit note"
                      className="p-1 text-amber-700 hover:bg-amber-100 rounded"
                    >
                      <Pencil className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>
              );
            }
            if (allShipped) return null;
            return (
              <div className="px-4 py-2 border-t border-gray-100 bg-gray-50">
                <button
                  type="button"
                  onClick={beginEdit}
                  className="inline-flex items-center gap-1.5 text-xs text-gray-600 hover:text-amber-700"
                >
                  <StickyNote className="w-3.5 h-3.5" /> Add note
                </button>
              </div>
            );
          })()}

          {/* Inline USPS tracking editor — opens via "Add tracking" or "Edit". */}
          {editingTracking && (
            <div className="px-4 py-3 bg-blue-50 border-t border-blue-100 space-y-2">
              <div className="text-xs font-medium text-blue-900 flex items-center gap-1.5">
                <Tag className="w-3.5 h-3.5" /> USPS tracking number from Palmstreet
              </div>
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={trackingInput}
                  onChange={(e) => setTrackingInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') { e.preventDefault(); submitTracking(); }
                    if (e.key === 'Escape') cancelEditTracking();
                  }}
                  placeholder="9400 1112 0204 1234 5678 90"
                  autoFocus
                  className="flex-1 px-3 py-2 text-sm font-mono border border-blue-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                />
                <button
                  onClick={submitTracking}
                  disabled={savingTracking}
                  className="px-3 py-2 text-sm font-medium bg-blue-600 hover:bg-blue-700 disabled:bg-gray-300 text-white rounded-lg"
                >
                  {savingTracking ? 'Saving…' : 'Save'}
                </button>
                <button
                  onClick={cancelEditTracking}
                  className="px-3 py-2 text-sm text-gray-700 hover:bg-blue-100 rounded-lg"
                >
                  Cancel
                </button>
              </div>
              {trackingErr && (
                <div className="text-xs text-red-700">{trackingErr}</div>
              )}
            </div>
          )}

          {/* Existing-label info row. Same layout for both flows; the
              available actions differ. */}
          {hasActiveLabel && !editingTracking && (
            <div className="px-4 py-2.5 bg-gray-50 border-t border-gray-100 flex items-center gap-3 flex-wrap text-xs">
              <div className="flex items-center gap-1.5 text-gray-700">
                <Truck className="w-3.5 h-3.5 text-gray-500" />
                <span className="font-mono">{shipment.trackingNumber || '(no tracking)'}</span>
              </div>
              {shipment.labelCost != null && !shipment.isTestLabel && (
                <span className="text-gray-500">${parseFloat(shipment.labelCost).toFixed(2)}</span>
              )}
              <span className="text-gray-400">
                {isPalmstreetRow ? 'Palmstreet USPS' : shipment.serviceCode}
              </span>
              <div className="ml-auto flex items-center gap-1">
                {/* Label PDF — exists for ShipStation rows AND for Palmstreet
                    rows that came through the Chrome extension flow. */}
                {(shipment.labelStoragePath || (!isPalmstreetRow)) && (
                  <button
                    onClick={() => downloadShipmentPdf(shipment, 'label', showToast)}
                    className="flex items-center gap-1 px-2 py-1 text-emerald-700 hover:bg-emerald-50 rounded"
                  >
                    <DownloadIcon className="w-3.5 h-3.5" /> Label
                  </button>
                )}
                {/* Packing slip — only Palmstreet flow currently provides this. */}
                {shipment.shippingSlipStoragePath && (
                  <button
                    onClick={() => downloadShipmentPdf(shipment, 'slip', showToast)}
                    className="flex items-center gap-1 px-2 py-1 text-emerald-700 hover:bg-emerald-50 rounded"
                  >
                    <DownloadIcon className="w-3.5 h-3.5" /> Slip
                  </button>
                )}
                {!allShipped && isPalmstreetRow && (
                  <>
                    <button
                      onClick={beginEditTracking}
                      className="flex items-center gap-1 px-2 py-1 text-gray-700 hover:bg-gray-100 rounded"
                    >
                      <Edit2 className="w-3.5 h-3.5" /> Edit
                    </button>
                    <button
                      onClick={onClearTracking}
                      className="flex items-center gap-1 px-2 py-1 text-gray-600 hover:bg-red-50 hover:text-red-600 rounded"
                    >
                      <RotateCcw className="w-3.5 h-3.5" /> Clear
                    </button>
                  </>
                )}
                {!allShipped && !isPalmstreetRow && (
                  <button
                    onClick={onVoidLabel}
                    className="flex items-center gap-1 px-2 py-1 text-gray-600 hover:bg-red-50 hover:text-red-600 rounded"
                  >
                    <RotateCcw className="w-3.5 h-3.5" /> Void
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Action buttons: differ by carrier. UPS gets the ShipStation
              Buy Label button; USPS gets a Palmstreet tracking entry button. */}
          {!allShipped && !editingTracking && (
            <div className="px-4 py-3 bg-gray-50 border-t border-gray-100 flex justify-end gap-2 flex-wrap">
              {onPrintItemLabels && (() => {
                // Same predicate as the tab-level button and the
                // BoxLabelSheet header tag (src/labels/BoxLabelSheet.jsx).
                const antItems = (box.items || []).filter(
                  i => (i.variety || '').toLowerCase() === 'anthurium'
                );
                if (antItems.length === 0) return null;
                return (
                  <button
                    type="button"
                    onClick={() => onPrintItemLabels(antItems)}
                    className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 text-sm font-medium rounded-lg"
                    title={`Print 2″×1″ labels for the ${antItems.length} Anthurium item${antItems.length === 1 ? '' : 's'} in this box`}
                  >
                    <Printer className="w-4 h-4" />
                    Print ANT labels
                    <span className="text-xs text-gray-500 ml-0.5">· {antItems.length}</span>
                  </button>
                );
              })()}
              {!hasActiveLabel && isUps && (
                <button
                  onClick={onBuyLabel}
                  className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-emerald-300 text-emerald-700 hover:bg-emerald-50 text-sm font-medium rounded-lg"
                >
                  <ShoppingCart className="w-4 h-4" /> Buy UPS Label
                </button>
              )}
              {!hasActiveLabel && isUsps && (
                <button
                  onClick={beginEditTracking}
                  className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-blue-300 text-blue-700 hover:bg-blue-50 text-sm font-medium rounded-lg"
                  title="Generate the label in Palmstreet, then paste the tracking number here"
                >
                  <Tag className="w-4 h-4" /> Add USPS Tracking
                </button>
              )}
              <button
                onClick={onShip}
                className="flex items-center gap-1.5 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 active:bg-emerald-800 text-white text-sm font-medium rounded-lg"
              >
                <Send className="w-4 h-4" /> Mark Shipped
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
