-- 0005 · Allow manual carrier entries (USPS via Palmstreet) in shipments.
-- For ShipStation-bought labels we always have weight, dims, ship-from
-- and ship-to. For USPS labels generated by Palmstreet the operator only
-- enters the tracking number; the rest of the metadata isn't useful and
-- isn't worth fabricating. Drop the NOT NULL on the fields that don't
-- apply to manual rows.
--
-- Idempotent.

alter table shipments alter column "weightOz" drop not null;
alter table shipments alter column "shipFrom" drop not null;
alter table shipments alter column "shipTo"   drop not null;

insert into applied_migrations (id) values ('0005_shipments_allow_manual_carrier')
  on conflict (id) do nothing;
