import { supabase, requireUser } from './_lib/supabase.js';
import { wrap, methodNotAllowed } from './_lib/respond.js';

// Routes:
//   GET  /api/shipments?saleId=X&userId=...
//     → all shipments for a sale (PackingView reads this on mount)
//
//   GET  /api/shipments?action=label-url&id=BOX&userId=...
//     → mints a 5-minute signed URL for the label PDF in Storage.
//       Falls back to a data: URL built from labelData for legacy
//       rows that pre-date the storage cutover.
//
//   POST /api/shipments  body: { action: 'record-tracking', shipmentBoxId, trackingNumber, userId }
//     → upserts a manual USPS row (label generated by Palmstreet, not ShipStation).
//
//   POST /api/shipments  body: { action: 'clear-tracking', shipmentBoxId, userId }
//     → deletes a manual USPS row. Refuses to delete real ShipStation labels;
//       use /api/shipstation { action: 'void-label' } for those.

const SIGNED_URL_TTL_SECONDS = 300; // 5 minutes — long enough to print, short enough to not leak

// Sentinel codes that identify a USPS row entered manually by the operator
// (i.e. not bought through ShipStation). Used as the carrierCode/serviceCode
// so the row is non-null + identifiable, and so clear-tracking can refuse
// to touch real ShipStation rows.
const PALMSTREET_CARRIER_CODE = 'palmstreet';
const PALMSTREET_SERVICE_CODE = 'palmstreet_usps';

export default wrap(async (req, res) => {
  const userId = req.method === 'GET' ? req.query?.userId : req.body?.userId;
  await requireUser(userId);

  switch (req.method) {
    case 'GET': {
      const action = req.query?.action;
      if (action === 'label-url') return labelUrl(req, res);
      return list(req, res);
    }
    case 'POST': {
      const action = req.body?.action;
      if (action === 'record-tracking') return recordTracking(req, res, userId);
      if (action === 'clear-tracking') return clearTracking(req, res);
      const e = new Error(`Unknown action: ${action}`); e.status = 400; throw e;
    }
    default:
      return methodNotAllowed(res, ['GET', 'POST']);
  }
});

async function list(req, res) {
  const saleId = req.query?.saleId;
  // Don't ship the heavy labelData blob when listing — clients only need
  // it on demand via the label-url action.
  let query = supabase
    .from('shipments')
    .select('id, "saleId", carrier, "carrierCode", "serviceCode", "trackingNumber", "labelCost", "labelStoragePath", "isTestLabel", "purchasedAt", "voidedAt"');
  if (saleId) query = query.eq('saleId', saleId);

  const { data, error } = await query;
  if (error) { const e = new Error(error.message); e.status = 500; throw e; }
  return res.status(200).json({ shipments: data || [] });
}

async function labelUrl(req, res) {
  const id = req.query?.id;
  if (!id) { const e = new Error('id required'); e.status = 400; throw e; }

  const { data: row, error } = await supabase
    .from('shipments')
    .select('id, "labelStoragePath", "labelData"')
    .eq('id', id)
    .maybeSingle();
  if (error) { const e = new Error(error.message); e.status = 500; throw e; }
  if (!row) { const e = new Error('Shipment not found'); e.status = 404; throw e; }

  if (row.labelStoragePath) {
    const { data: signed, error: sErr } = await supabase
      .storage
      .from('shipping-labels')
      .createSignedUrl(row.labelStoragePath, SIGNED_URL_TTL_SECONDS);
    if (sErr) { const e = new Error(sErr.message); e.status = 500; throw e; }
    return res.status(200).json({ url: signed.signedUrl });
  }

  if (row.labelData) {
    return res.status(200).json({ url: `data:application/pdf;base64,${row.labelData}` });
  }

  const e = new Error('No label PDF available for this shipment'); e.status = 404; throw e;
}

async function recordTracking(req, res, userId) {
  let { shipmentBoxId, trackingNumber, matchByOrderId } = req.body || {};
  const trim = (trackingNumber || '').trim();
  if (!trim) { const e = new Error('trackingNumber required'); e.status = 400; throw e; }

  // Resolve shipmentBoxId from a Palmstreet order number when the caller
  // (e.g. the Chrome extension) only knows the order id. All items in a
  // box share the same recipient address so the join via orderId is safe.
  if (!shipmentBoxId && matchByOrderId) {
    const { data: matches } = await supabase
      .from('inventory_items')
      .select('"shipmentBoxId"')
      .eq('orderId', String(matchByOrderId).trim())
      .not('shipmentBoxId', 'is', null)
      .limit(1);
    shipmentBoxId = matches?.[0]?.shipmentBoxId || null;
    if (!shipmentBoxId) {
      const e = new Error(`No shipment box found for Palmstreet order ${matchByOrderId}`);
      e.status = 404; throw e;
    }
  }
  if (!shipmentBoxId) {
    const e = new Error('shipmentBoxId or matchByOrderId required'); e.status = 400; throw e;
  }

  // Refuse to overwrite a real ShipStation row via this endpoint — those
  // must go through the void-label flow first.
  const { data: existing } = await supabase
    .from('shipments')
    .select('id, "carrierCode", "voidedAt"')
    .eq('id', shipmentBoxId)
    .maybeSingle();
  if (existing && existing.carrierCode !== PALMSTREET_CARRIER_CODE) {
    const e = new Error('A ShipStation label already exists for this box — void it first');
    e.status = 409; throw e;
  }

  // Pull the box's saleId so the row joins back to the sale event.
  const { data: items } = await supabase
    .from('inventory_items')
    .select('"saleId"')
    .eq('shipmentBoxId', shipmentBoxId)
    .limit(1);
  const saleId = items?.[0]?.saleId || null;

  const row = {
    id: shipmentBoxId,
    saleId,
    carrier: 'usps',
    carrierCode: PALMSTREET_CARRIER_CODE,
    serviceCode: PALMSTREET_SERVICE_CODE,
    packageCode: 'package',
    trackingNumber: trim,
    isTestLabel: false,
    purchasedAt: existing?.purchasedAt || new Date().toISOString(),
    purchasedBy: userId,
    voidedAt: null,
    voidedBy: null,
  };

  const { data: saved, error: saveErr } = await supabase
    .from('shipments')
    .upsert(row)
    .select()
    .single();
  if (saveErr) { const e = new Error(saveErr.message); e.status = 500; throw e; }

  return res.status(200).json({ shipment: saved });
}

async function clearTracking(req, res) {
  const { shipmentBoxId } = req.body || {};
  if (!shipmentBoxId) { const e = new Error('shipmentBoxId required'); e.status = 400; throw e; }

  // Only allow clearing manual Palmstreet rows here. ShipStation labels
  // must be voided through the ShipStation void endpoint to also refund.
  const { data: existing } = await supabase
    .from('shipments')
    .select('id, "carrierCode"')
    .eq('id', shipmentBoxId)
    .maybeSingle();
  if (!existing) { const e = new Error('No tracking entry for this box'); e.status = 404; throw e; }
  if (existing.carrierCode !== PALMSTREET_CARRIER_CODE) {
    const e = new Error('This is a ShipStation label — void via Buy Label flow instead');
    e.status = 409; throw e;
  }

  const { error } = await supabase.from('shipments').delete().eq('id', shipmentBoxId);
  if (error) { const e = new Error(error.message); e.status = 500; throw e; }
  return res.status(200).json({ ok: true });
}
